# Downside Risk Measures

### Semi-deviation

We argued previously that asset returns are not usually normally distribued. So, a main concern for investors is the possibilty of large negative return on the portfoloio they are holding. We want to go beyond volatility as we currently know it; average or standard deviation around the mean.

The first step beyond volatility is **semi-volatility** or **semi-deviation**, which is defined as: the volatility of the sub-sample of below-average or below zero returns. To calculate this we truncate the return distribution and we only focus on the outcomes below the mean or below zero. This is more optimal as it's more important to investors to focus on volatility in losses than volatility in losses and gains. 

Semi deviation is given by the following equation

$$\sigma_{semi} = \sqrt{\frac{1}{N}\sum_{R_t \leq \bar{R}} \left ( R_t - \bar{R}\right)^2},$$

where $N$ is the number of returns which fall below the mean (or zero). However, this still merely just tells us about the volatility of the losses of returns.

### Value at Risk - Motivation

In an attempt to have a focus on an extreme downside we introduce a new very useful concept called VaR or 'Value at Risk', this represents the maximum 'expected' loss over a given time period.

Value at Risk (VaR) is defined as the maximum potential loss threshold, this is accompanied by a specified confidence level and a time period.

### Distribution Beyond VaR

If we consider VaR at for example a 99% confidence interval, we would essentially be 'throwing away' 1% of meaningful data. It's actually what happens beyond VaR that may be a greater concern to investors as opposed to just looking at the exact VaR number. In this context it's useful to introduce another risk indicator which we call 'Beyond Value at Risk' or 'Conditional Value at Risk', CVaR in short. In this case we are going to be looking at the expected loss beyond VaR, specifically the average of the distribution beyond VaR.

CVaR is given by the following equation

$$CVaR = -E(R\mid R\leq-VaR) = \frac{-\int^{-VaR}_{-\infty}x \cdot f_R(x)\mathop{\mathrm{d}x}}{F_R(-VaR)},$$

where $f_r$ and $F_R$ are density and cumulative distribution functions respectively.

In conclusion, uncertainty on the downside is what investors are most concerned about and volatility alone does not do that justice.

# Lab Session - Deviations from Normality

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import edhec_risk_kit as erk

In [2]:
hfi = erk.get_hfi_returns()
hfi.head()

Convertible Arbitrage  CTA Global  Distressed Securities  \
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   

         Emerging Markets  Equity Market Neutral  Event Driven  \
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275

In [3]:
pd.concat([hfi.mean(), hfi.median(), hfi.mean()>hfi.median()], axis = 'columns')

0       1      2
Convertible Arbitrage   0.005508  0.0065  False
CTA Global              0.004074  0.0014   True
Distressed Securities   0.006946  0.0089  False
Emerging Markets        0.006253  0.0096  False
Equity Market Neutral   0.004498  0.0051  False
Event Driven            0.006344  0.0084  False
Fixed Income Arbitrage  0.004365  0.0055  False
Global Macro            0.005403  0.0038   True
Long/Short Equity       0.006331  0.0079  False
Merger Arbitrage        0.005356  0.0060  False
Relative Value          0.005792  0.0067  False
Short Selling          -0.001701 -0.0053   True
Funds Of Funds          0.004262  0.0052  False

## Skewness

In almost every case the mean is greater than the median, this implies negative skewness. 

Recall the formula for skewness

$$S(R) = \frac{E[(R - E(R))^3]}{[Var(R)]^{3/2}} = \frac{E[(R - E(R))^3]}{\sigma_R^{3}}.$$


In [4]:
erk.skewness(hfi).sort_values()

Fixed Income Arbitrage   -3.940320
Convertible Arbitrage    -2.639592
Equity Market Neutral    -2.124435
Relative Value           -1.815470
Event Driven             -1.409154
Merger Arbitrage         -1.320083
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Long/Short Equity        -0.390227
Funds Of Funds           -0.361783
CTA Global                0.173699
Short Selling             0.767975
Global Macro              0.982922
dtype: float64

In [5]:
# compare with scipy
import scipy.stats

In [6]:
scipy.stats.skew(hfi)

array([-2.63959223,  0.17369864, -1.30084204, -1.16706749, -2.12443538,
       -1.40915356, -3.94032029,  0.98292188, -0.39022677, -1.32008333,
       -1.81546975,  0.76797484, -0.36178308])

In [7]:
erk.skewness(hfi)

Convertible Arbitrage    -2.639592
CTA Global                0.173699
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Equity Market Neutral    -2.124435
Event Driven             -1.409154
Fixed Income Arbitrage   -3.940320
Global Macro              0.982922
Long/Short Equity        -0.390227
Merger Arbitrage         -1.320083
Relative Value           -1.815470
Short Selling             0.767975
Funds Of Funds           -0.361783
dtype: float64

In [8]:
# paranoid check 
import numpy as np

In [9]:
hfi.shape

(263, 13)

In [10]:
normal_rets = np.random.normal(0, .15, size = (26300, 1))

In [11]:
erk.skewness(normal_rets)

-0.010630826448133953

In [12]:
scipy.stats.skew(normal_rets)

array([-0.01063083])

## Kurtosis

Recall the formula

$$K(R) = \frac{E[(R - E(R))^4]}{[Var(R)]^{2}} = \frac{E[(R - E(R))^4]}{\sigma_R^{4}}.$$

In [13]:
erk.kurtosis(hfi)

Convertible Arbitrage     23.280834
CTA Global                 2.952960
Distressed Securities      7.889983
Emerging Markets           9.250788
Equity Market Neutral     17.218555
Event Driven               8.035828
Fixed Income Arbitrage    29.842199
Global Macro               5.741679
Long/Short Equity          4.523893
Merger Arbitrage           8.738950
Relative Value            12.121208
Short Selling              6.117772
Funds Of Funds             7.070153
dtype: float64

In [14]:
# scipy returns the excess kurtosis (kurtosis - 3)
scipy.stats.kurtosis(hfi)

array([20.28083446, -0.04703963,  4.88998336,  6.25078841, 14.21855526,
        5.03582817, 26.84219928,  2.74167945,  1.52389258,  5.73894979,
        9.12120787,  3.11777175,  4.07015278])

In [15]:
scipy.stats.jarque_bera(normal_rets)

Jarque_beraResult(statistic=0.636361948077156, pvalue=0.7274711231138553)

In [16]:
# not working as we want it to, all data is being used instead of column specific
scipy.stats.jarque_bera(hfi)

Jarque_beraResult(statistic=25656.585999171326, pvalue=0.0)

In [17]:
erk.is_normal(normal_rets)

True

In [18]:
# same problem as before
erk.is_normal(hfi)

False

In [19]:
# aggregate is a pandas method that applies a function to each column
hfi.aggregate(erk.is_normal)

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities     False
Emerging Markets          False
Equity Market Neutral     False
Event Driven              False
Fixed Income Arbitrage    False
Global Macro              False
Long/Short Equity         False
Merger Arbitrage          False
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool

In [20]:
# test with ffme data
ffme = erk.get_ffme_returns()

In [21]:
erk.skewness(ffme)

SmallCap    4.410739
LargeCap    0.233445
dtype: float64

In [22]:
erk.kurtosis(ffme)

SmallCap    46.845008
LargeCap    10.694654
dtype: float64

In [23]:
ffme.aggregate(erk.is_normal)

SmallCap    False
LargeCap    False
dtype: bool